FROM node:18-alpine

WORKDIR /app

# Copy frontend only
COPY frontend ./frontend

# Go to frontend directory
WORKDIR /app/frontend

# Clean install
RUN rm -rf node_modules yarn.lock || true && \
    yarn cache clean && \
    yarn install --network-timeout 1000000 && \
    yarn build

# Install serve
RUN npm install -g serve

# Expose port
EXPOSE 3000

# Start from build directory
CMD ["serve", "-s", "build", "-p", "3000"]
