FROM node:18

WORKDIR /app

# Copy everything
COPY . .

# Install and build frontend
RUN cd frontend && yarn install && yarn build

# Install serve
RUN npm install -g serve

# Expose port
EXPOSE 3000

# Start app
CMD ["serve", "-s", "frontend/build", "-l", "3000"]
